# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T10:52:21+00:00



import argparse
import json
import os
from typing import *
from typing import Optional, Union

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import BaseSecurity, HTTPBasic
from fastapi import Path, Query
from pydantic import conint, constr
from starlette.requests import Request

from models import (
    AccountsV1AuthTokenPromotion,
    AccountsV1CredentialCredentialAws,
    AccountsV1CredentialCredentialPublicKey,
    AccountsV1SecondaryAuthToken,
    V1CredentialsAWSGetResponse,
    V1CredentialsPublicKeysGetResponse,
)

app = MCPProxy(
    contact={
        'email': 'support@twilio.com',
        'name': 'Twilio Support',
        'url': 'https://support.twilio.com',
    },
    description='This is the public Twilio REST API.',
    license={
        'name': 'Apache 2.0',
        'url': 'https://www.apache.org/licenses/LICENSE-2.0.html',
    },
    termsOfService='https://www.twilio.com/legal/tos',
    title='Twilio - Accounts',
    version='1.42.0',
    servers=[{'url': 'https://accounts.twilio.com'}],
)


@app.post(
    '/v1/AuthTokens/Promote',
    description=""" Promote the secondary Auth Token to primary. After promoting the new token, all requests to Twilio using your old primary Auth Token will result in an error. """,
    tags=['auth_token_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def update_auth_token_promotion():
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/v1/AuthTokens/Secondary',
    description=""" Delete the secondary Auth Token from your account """,
    tags=['auth_token_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def delete_secondary_auth_token():
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/AuthTokens/Secondary',
    description=""" Create a new secondary Auth Token """,
    tags=['auth_token_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def create_secondary_auth_token():
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Credentials/AWS',
    description=""" Retrieves a collection of AWS Credentials belonging to the account used to make the request """,
    security=[
        HTTPBasic(name="None"),
    ],
)
def list_credential_aws(
    page_size: Optional[conint(ge=1, le=1000)] = Query(None, alias='PageSize'),
    page: Optional[conint(ge=0)] = Query(None, alias='Page'),
    page_token: Optional[str] = Query(None, alias='PageToken'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Credentials/AWS',
    description=""" Create a new AWS Credential """,
    tags=['auth_token_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def create_credential_aws(request: Request):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/v1/Credentials/AWS/{Sid}',
    description=""" Delete a Credential from your account """,
    tags=['public_key_credentials_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def delete_credential_aws(
    sid: constr(pattern=r'^CR[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    )
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Credentials/AWS/{Sid}',
    description=""" Fetch the AWS credentials specified by the provided Credential Sid """,
    tags=['auth_token_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_credential_aws(
    sid: constr(pattern=r'^CR[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    )
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Credentials/AWS/{Sid}',
    description=""" Modify the properties of a given Account """,
    tags=['auth_token_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def update_credential_aws(
    sid: constr(pattern=r'^CR[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    ),
    request: Request = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Credentials/PublicKeys',
    description=""" Retrieves a collection of Public Key Credentials belonging to the account used to make the request """,
    security=[
        HTTPBasic(name="None"),
    ],
)
def list_credential_public_key(
    page_size: Optional[conint(ge=1, le=1000)] = Query(None, alias='PageSize'),
    page: Optional[conint(ge=0)] = Query(None, alias='Page'),
    page_token: Optional[str] = Query(None, alias='PageToken'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Credentials/PublicKeys',
    description=""" Create a new Public Key Credential """,
    tags=['auth_token_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def create_credential_public_key(request: Request):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/v1/Credentials/PublicKeys/{Sid}',
    description=""" Delete a Credential from your account """,
    tags=['auth_token_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def delete_credential_public_key(
    sid: constr(pattern=r'^CR[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    )
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v1/Credentials/PublicKeys/{Sid}',
    description=""" Fetch the public key specified by the provided Credential Sid """,
    tags=['public_key_credentials_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def fetch_credential_public_key(
    sid: constr(pattern=r'^CR[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    )
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v1/Credentials/PublicKeys/{Sid}',
    description=""" Modify the properties of a given Account """,
    tags=['auth_token_management'],
    security=[
        HTTPBasic(name="None"),
    ],
)
def update_credential_public_key(
    sid: constr(pattern=r'^CR[0-9a-fA-F]{32}$', min_length=34, max_length=34) = Path(
        ..., alias='Sid'
    ),
    request: Request = ...,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
